Feature newsweek home
Lameck1/Using-Bootstrap pull request #1
Opened 2020-10-14 09:45 UTC by Div685

## About The Project

This project clones The [Newsweek](https://www.newsweek.com/), an American weekly news magazine which uses majorly bootstrap for the styling of the website.

The project has involved the application of bootstrap classes to HTML elements to achieve the desirable styling on the original page.

## Built With
- HTML
- CSS
- Bootstrap 4
- Fontawesome

## Getting Started
- Clone this repo https://github.com/Lameck1/Using-Bootstrap
- To get a local copy up and running follow these simple steps.
Install dependencies:

```
npm install
```

or

```
yarn install
```

2020-10-14 10:40 UTC, arslanbisharat requested changes
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet. You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

- [ ]  In Bootstrap projects make sure to less use the styles.css file for styles that could be done using Bootstrap classes since that's the main goal of the exercise. Things like font-weight, flex justifications, display, etc could be implemented completely with Bootstrap classes. [Please refer to the main page of bootstrap to learn more about bootstrap. ](https://getbootstrap.com/docs/4.5/getting-started/introduction/)

- [ ] Please add non-necessary files like vscode to gitignore

- [ ] Please add these two folders into one folder. This will make your repo more professional. 
![chrome-capture (45)](https://user-images.githubusercontent.com/58504655/95974938-fd8b9580-0e2e-11eb-9cc7-b9e945182284.jpg)

- [ ] Please have a look at the attachment below. The newsletter image has more width on the original page.

**Clone**

![chrome-capture (44)](https://user-images.githubusercontent.com/58504655/95975270-5d823c00-0e2f-11eb-97dd-5816b96a0568.jpg)

- [ ] There is a breakdown after each item on the original page. But your clone is missing. 

**Clone**

![chrome-capture (47)](https://user-images.githubusercontent.com/58504655/95975618-d4b7d000-0e2f-11eb-972b-727d97072dd4.jpg)

**Original** 

![chrome-capture (46)](https://user-images.githubusercontent.com/58504655/95975664-e1d4bf00-0e2f-11eb-9fb8-7d0ed1aced52.jpg)

- [ ] On the original page, section **The Debate** is present before **More Stories** but on your clone is the opposite. 

-[ ] Footer on tablet and small screen modes are not aligned correctly. please work on it. 

**Clone**

![chrome-capture (48)](https://user-images.githubusercontent.com/58504655/95976310-bbfbea00-0e30-11eb-98ea-9b729b254998.jpg)

**Original** 

![chrome-capture (49)](https://user-images.githubusercontent.com/58504655/95976368-d5049b00-0e30-11eb-814d-498f9439e1e3.jpg)

-[ ] There should be space and breakdown after the subscribe section on the small screen. 

**Clone**

![chrome-capture (51)](https://user-images.githubusercontent.com/58504655/95976575-290f7f80-0e31-11eb-88fb-f6d7c240fb46.jpg)

**Original**

![chrome-capture (52)](https://user-images.githubusercontent.com/58504655/95976602-33ca1480-0e31-11eb-9897-d294c52072c7.jpg)


**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-10-14 10:40 UTC, arslanbisharat commented on css/style.css
> +  line-height: 18px;
This goal can be done with bootstrap.

2020-10-14 10:40 UTC, arslanbisharat commented on css/style.css
> +  height: 28px;
The goals can be achieved with bootstrap.

2020-10-14 10:40 UTC, arslanbisharat commented on css/style.css
> +  flex: none;
This goal can be done with bootstrap.

2020-10-14 10:40 UTC, arslanbisharat commented on css/style.css
> +  width: 200px;
This goal can be done with bootstrap.

2020-10-14 10:40 UTC, arslanbisharat commented on css/style.css
> +  height: 32px;
This goal can be done with bootstrap.

2020-10-14 10:40 UTC, arslanbisharat commented on css/style.css
> +  display: grid;
This goal can be done with bootstrap.

2020-10-14 10:40 UTC, arslanbisharat commented on css/style.css
> +  display: block;
This goal can be done with bootstrap.

2020-10-14 10:40 UTC, arslanbisharat commented on css/style.css
> +  width: 100%;
This goal can be done with bootstrap.

2020-10-14 10:40 UTC, arslanbisharat commented on css/style.css
> +  height: 1px;
This goal can be done with bootstrap.

2020-10-14 10:40 UTC, arslanbisharat commented on css/style.css
> +  content: "";
Why this empty is here?

2020-10-14 10:40 UTC, arslanbisharat commented on css/style.css
> +/* @media (min-width: 768px) {
Please remove the commented code.

2020-10-14 11:19 UTC, Lameck1 commented on css/style.css
> +  display: block;
Hello, please lead me to a resource that would teach me how to implement pseudo selection with bootstrap.
I can't seem to find anything about implementing ::before and ::after with pure bootstrap. I am also kindly asking you to investigate why we decided to implement pseudo selections with CSS. Lastly, the project instructions tell us to use bootstrap as much as possible, not on everything, there are some styling on the page that are not just achievable with pure bootstrap, i.e. some sort of calculated fixed positioning, I was hoping you get to understand this and don't force us to undo the entire CSS.

2020-10-14 11:20 UTC, Lameck1 commented on css/style.css
> +  width: 100%;
Still having a problem with implementing pseudo selection with bootstrap, please lead us to a resource or at least give us an idea.

2020-10-14 11:23 UTC, Lameck1 commented on css/style.css
> +  height: 1px;
These are pseudo selections properties, they are trying to achieve a specific styling not achievable by bootstrap. Please give us an idea of how to do this with bootstrap.

2020-10-14 11:25 UTC, Lameck1 commented on css/style.css
> +  content: "";
The content is empty because we are trying to achieve only a background without any content.

2020-10-14 11:25 UTC, Lameck1 commented on css/style.css
> +/* @media (min-width: 768px) {
Sure, that will be removed.

2020-10-14 11:27 UTC, Lameck1 commented on css/style.css
> +  height: 32px;
We will do our best in this area but the bootstrap implementation of it is not working well. Any ideas?

2020-10-14 11:28 UTC, Lameck1 commented on css/style.css
> +  width: 200px;
Bootstrap is not giving us the desired width at this point, we will do our best though.

2020-10-14 11:31 UTC, Lameck1 commented on css/style.css
> +  flex: none;
I would like to beg you to let this slide. This is an implementation of the official Newsweek icon. We can do it with bootstrap but it doesn't look good and we are sure TSEs won't accept an ugly implementation.

2020-10-14 11:31 UTC, Lameck1 commented on css/style.css
> +  height: 28px;
I would like to beg you to let this slide. This is an implementation of the official Newsweek icon. We can do it with bootstrap but it doesn't look good and we are sure TSEs won't accept an ugly implementation.

2020-10-14 11:32 UTC, Lameck1 commented on css/style.css
> +  line-height: 18px;
Agreed, we will make changes here.

2020-10-14 12:13 UTC, arslanbisharat commented on css/style.css
> +  height: 32px;
THANK YOU LOOKING FORWARD

2020-10-14 12:13 UTC, arslanbisharat commented on css/style.css
> +  width: 200px;
Thank you

2020-10-14 12:14 UTC, arslanbisharat commented on css/style.css
> +  content: "";
okay

2020-10-14 12:18 UTC, arslanbisharat commented on css/style.css
> +  line-height: 18px;
Thank You

2020-10-14 12:19 UTC, arslanbisharat commented on css/style.css
> +  height: 28px;
Next, TSE will review it and tell you a reasonable answer.

2020-10-14 12:19 UTC, arslanbisharat commented on css/style.css
> +  flex: none;
Let the next TSE have a look.

2020-10-14 12:34 UTC, arslanbisharat commented
### Apologizing About My mistake. 
Hello Team,
All TSEs are human so, we make mistakes too. I would like to apologize to both of you to please forgive me for my mistake. I didn't notice the pseudo-classes and asked you to make changes in code. 
Regards,
Arslan Bisharat.

2020-10-14 18:48 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've done an excellent job so far.__

- Your responsiveness is sweet :100: 
- You did well in fixing the changes recommended by the previous reviewer :+1: 
- All linter checks are green :green_circle: 

_Overall, the project is almost complete. Let's make this correction and submit another review request. Please check my points below and fix them as appropriate._

**[ REQUIRED CHANGES ]**

- [x] The height of the newsletter section is not the same as the original. Kindly fix it.

Original page:
![19-32-11](https://user-images.githubusercontent.com/26856491/96030770-5c173a80-0e54-11eb-9df0-d963f277931d.png)

Your clone:
![19-31-37](https://user-images.githubusercontent.com/26856491/96030789-60435800-0e54-11eb-8a09-53568fbf8968.png)

- [x] The Newsweek logo is not centralized in the top navbar

Original page:
![original](https://user-images.githubusercontent.com/26856491/96032071-15c2db00-0e56-11eb-9101-37db1a4ff5f4.png)

Your clone:
![clone](https://user-images.githubusercontent.com/26856491/96032058-0e9bcd00-0e56-11eb-8277-5b9d82eb12ff.png)


**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech), or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-10-15 16:41 UTC, arslanbisharat requested changes
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet. You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

                                            ### LARGE SCREEN

- [ ] Navbar in the large screen is not as present on the original page. I have already told you to change it in our chat in slack and during our video call. Please work on it. If you have any questions please reach me out or have a 1:1 appointment with a full-time TSE for greater explanation. 

- [ ] Text in the **subscribe** section is not correctly aligned as present on the original page. Please work on it. 

**Clone**

![chrome-capture (88)](https://user-images.githubusercontent.com/58504655/96158647-2a25d700-0f2d-11eb-9b94-7b34ef69d2b7.jpg)

**Original**

![chrome-capture (89)](https://user-images.githubusercontent.com/58504655/96158765-46c20f00-0f2d-11eb-94fc-822a83f374be.jpg)

- [ ] Under the Newsweek logo there is a very small gap on the original page but in your clone, it has more gaps. 

**Clone**

![chrome-capture (90)](https://user-images.githubusercontent.com/58504655/96159105-b3d5a480-0f2d-11eb-9e05-9cee1ec820ac.jpg)

**Original**

![chrome-capture (91)](https://user-images.githubusercontent.com/58504655/96159166-c7810b00-0f2d-11eb-962b-1f3e0ed20bf6.jpg)

                                         ### MEDIUM SCREEN

- [ ] In your clone on the medium screen there is a gap between the navbar and other sections but on the original page, there is no gap. Please have a look below. 

 **Clone**

![chrome-capture (92)](https://user-images.githubusercontent.com/58504655/96159682-6148b800-0f2e-11eb-89b1-5ad6969f57ae.jpg)

**Original**

![chrome-capture (93)](https://user-images.githubusercontent.com/58504655/96159787-7faeb380-0f2e-11eb-94e6-c7a94cadc518.jpg)


                                            ### SMALL SCREEN

- [ ] In your clone on the medium screen there is a gap between the navbar and other sections but on the original page, there is no gap. Please have a look below. 

 **Clone**

![chrome-capture (92)](https://user-images.githubusercontent.com/58504655/96159682-6148b800-0f2e-11eb-89b1-5ad6969f57ae.jpg)

**ORIGINAL**

![chrome-capture (94)](https://user-images.githubusercontent.com/58504655/96160213-17140680-0f2f-11eb-857b-b20b40732b0e.jpg)


**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-10-15 19:49 UTC, arslanbisharat approved these changes
Congratslutons Approved 🎉
Hello Developer 👋
You are on 🔥
Thank you so much for making those changes and I am very happy to approve the project. You have done a great job. 👏
Please keep working hard and move forward with your curriculum.
Looking forward to seeing your next project. 😄
---------------------------------------------------------------------------------------------------------------
**To highlight**
- The cloned page is rendering as it should and meets all the project specifications.
-  CSS is clean.
-  The markup as well has no errors nor warnings to show. Good job with that.
-  The repo has followed all the guidelines there are to follow.
-  All the required tasks have been fulfilled in this project.
-  Congratulations on the splendid job👍
Now you can merge the branches and move forward with your curriculum. 🎆 

**Optional** I have given some suggestions below. I would highly recommend you to do that. 

**Optional** Please update the image in the readme. 

**OPTIONAL** If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 

I am very excited to see your next project.

**Happy Coding**:smiley:
------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) slack: @arslanbisharat

2020-10-15 20:24 UTC, merged